export interface Interfaces {
  src: string;
  title: string;
  url: string;
}
export interface decodedToken {
  authorities: string[];
  client_id: string;
  exp: number;
  id: number;
  jti: string;
  renterEmail: string;
  renterImg: string;
  renterListRented: any[];
  renterName: string;
  scope: string[];
  user_name: string;
}
export interface url {
  url: string;
}
export interface login {
  username: string;
  password: string;
}
// Generated by https://quicktype.io

export interface SignUp {
  renterEmail: string;
  renterEnabled: boolean;
  renterName: string;
  renterPassword: string;
  renterImg?: string;
}

// Generated by https://quicktype.io

export interface tokengenerated {
  access_token: string;
  expires_in: number;
  id: null;
  jti: string;
  refresh_token: string;
  renterEmail: string;
  renterListRented: any[];
  renterName: string;
  scope: string;
  token_type: string;
}
export interface RootProductPrice {
  status: string;
  code: string;
  message: string;
  data: DataProdPrice;
}

// Generated by https://quicktype.io

export interface RootProdFee {
  status: string;
  code: string;
  message: string;
  data: DataProdFee;
}

export interface DataProdFee {
  all_feeDeelays: AllFeeDeelay[];
}

export interface AllFeeDeelay {
  charge_per_day: number;
  id_fee: number;
}

export interface DataProdPrice {
  all_prices: Allprice[];
}

export interface Allprice {
  id_fee: number;
  price_per_day: number;
}
export interface RootResponse {
  status: string;
  code: string;
  message: string;
  data: Data;
}
export interface Data {
  list_ofProducts: ListofProduct[];
}

export interface ListofProduct {
  id: string;
  product_comments: Productcomment[];
  product_rents: Productrent[];
  product_type: string;
  product_imgs: Productimg[];
  product_in_inventary: boolean;
  product_name: string;
  product_name_sub_type: string;
}

export interface Productimg {
  id: number;
  url: string;
}

export interface Productrent {
  rent_days: number;
  rent_id: number;
  rent_real_cost: number;
  rent_closed: string;
  rent_by: string;
  rent_costs: number;
  rent_real_days: number;
}

export interface Productcomment {
  comment_by: string;
  comment: string;
  comment_id: number;
}
// Generated by https://quicktype.io

export interface UserStatusCombo {
  user_auth: boolean;
  user_authoritie: string;
}

// Generated by https://quicktype.io

export interface StatusSuccessProdType {
  status: string;
  code: string;
  message: string;
  data: DataProdType;
}

export interface DataProdType {
  allProductsType: AllProductsType[];
}

export interface AllProductsType {
  id: number;
  productType: string;
}

// Generated by https://quicktype.io

export interface StatusSuccessProdSubType {
  status: string;
  code: string;
  message: string;
  data: DataProdSubType;
}

export interface DataProdSubType {
  allProductsSubTypes: AllProductsSubType[];
}

export interface AllProductsSubType {
  listOfImages: ListOfImage[];
  id: number;
  productSubType: string;
}

export interface ListOfImage {
  id: number;
  url: string;
}

// Generated by https://quicktype.io

export interface StattusSuccessImges {
  status: string;
  code: string;
  message: string;
  data: DataAllImages;
}

export interface DataAllImages {
  allImages: AllImage[];
}

export interface AllImage {
  id: number;
  url: string;
}

export interface RootObjectProduct {
  status: string;
  code: string;
  message: string;
  data: Data;
}

export interface RootProduct {
  product: Product;
}

export interface Product {
  product_comments: any[];
  product_rents: ProductSelectedRent[];
  product_type: string;
  product_imgs: ProductSelectedimg[];
  product_in_inventary: boolean;
  id: number;
  product_name_sub_type: string;
  product_name: string;
}

export interface ProductSelectedimg {
  id: number;
  url: string;
}

export interface ProductSelectedRent {
  rent_days: number;
  rent_id: number;
  rent_real_cost: number;
  rent_closed: string;
  rent_by: string;
  rent_costs: number;
  rent_real_days: number;
}
